
export interface Metafield {
  fileType: string,
  operator: string,
  bankName: string,
  vendor: string,
  fileSource: string,
  xmlname: string
}

export interface Demographic {
  //userId: number
  enrollmentType: string,
  aofNo: string,
  bccCode: string,
  custType: string,
  salutation: string,
  custName: string,
  custMiddleName: string,
  custLastName: string,
  custTittle: string,   //
  dateAndTime: string,  //
  dDate: string,         //
  relationshipName: string,
  relationshipType: string,
  cusrMartialStatus: string,
  custMobileNumber: string,
  custEmailId: string,
  custDob: string,
  custAge: string,
  custSex: string,
  custPlaceofBirth: string,
  custNationality: string,
  custLanguageCode: string,
  custForm60or61: string,
  custFORMPANCardNumber: string,
  custAddress1: string,
  custAddress2: string,
  custAddress3: string,
  custPresentLandmark: string,
  custPresentLocality: string,
  custPresentPostOffice: string,
  censusCode: string,
  custVillage: string,
  custCityCode: string,
  custSubDist: string,
  custDistrict: string,
  custStateCode: string,
  custCountry: string,
  custPinNumber: string,
  custPermAddress1: string,
  custPermAddress2: string,
  custPermAddress3: string,
  custPermLandmark: string,
  custPermLocality: string,
  custPermPostOffce: string,
  censusCodeForCustVill: string,
  custPermVillage: string,
  custPermCityCode: string,
  custPermSubDist: string,
  custPermDistrict: string,
  custPermStateCode: string,
  permCountry: string,
  custPermPincode: string,
  identityDocType: string,
  identityDocNumber: string,
  idIssuedBy: string,
  idIssuePlace: string,
  idIssueDate: string,
  addressProofDocType: string,
  addressProofDocNumber: string,
  addrIssuedBy: string,
  addrIssuePlace: string,
  addrIssueDate: string,
  custAadhaarNo: string,
  custCommunityCode: string,
  custOcupationCode: string,
  lineOfBusiness: string,
  custEmployerType: string,
  educationalQualification: string,
  annualIncome: string,
  custIncomeSource: string,
  custVehicleType: string,
  custHouseType: string,
  ownShares: string,
  ownMutualFund: string,
  ownGold: string,
  ownBankFixedDeposit: string,
  ownNSCKVC: string,
  ownPPF: string,
  ownRBIBond: string,
  ownProperty: string,
  otherSavings: string,
  carLoan: string,
  housingLoan: string,
  consumerLoan: string,
  educationalLoan: string,
  businessAgricultureLoan: string,
  custResidencePeriod: string,
  custNetworth: string,
  incomeRecptMode: string,
  custTaxSlab: string,
  riskType: string,
  politicallyExposed: string,
  custPANCardPresense: string,
  applicantName: string,
  cisCode: string,
  bsrCode: string,
  domesticRisk: string,
  crossBorderRisk: string,
  countryofRisk: string,
  segmentCode: string,
  domicile: string,
  custResidentType: string,
  customerEvaluationRequired: string,
  nomineeRelation: string,
  nomineeTitleCode: string,
  nomineeName: string,
  nomineeLastName: string,
  nomineeAddress: string,
  nomineeTelephone: string,
  nomineeAge: string,
  nomineeMinor: string,
  nomineeDOB: string,
  guardianName: string,
  guardianAddress1: string,
  authCode: string,
  UIDToken: string,
  VID: string,
  rrn: string,
  eKYCConsentFlag: string,
  uploadedDate: string,
  uploadedTime: string,
  relationshipTitle: string,
  mobileCountryCode: string,
  atmFacilityRequired: string,
  atmCardStatus: string,
  stmtFrequency: string,
  accSubType: string,
  creditThreshold: string,
  debitThreshold: string,
  relFirstName: string,
  relLastName: string,
  permAddressType: string,
  presentAddressType: string,
  idExpiryDate: string,
  motherTitle: string,
  motherFirstName: string,
  motherLastName: string,
  smsRequired: string,
  custAnnualCredit: string,
  branch: string,
  productCode: string,
  interestCategory: string,
  DBTFlag: string,
  FATCAFlag: string
}

export interface UserEnroll {
  userName: string,
  metafield: Metafield,
  demographic: Demographic,

  custPhoto: {
    isEncrypted: string,
    aofNo: string,
    binarySubType: string,
    binaryData: string
  },
  custSign: {
    isEncrypted: string,
    aofNo: string,
    binarySubType: string
  },
  custIdProof: Array<object>,
  custAddrProof: Array<object>,
  custFpIso: Array<object>,
  custFpWsq: Array<object>,


  binary_data: {
    customerphoto: string,
    custIdProofFront: string,
    custIdProofBack: string,
    signature: string
  }
  additional_data: {
    userId: string,
    client_app_ver: string,
    platform: string,
    client_appType: string,
    vendorId: string,
    timeEpoch: string
  }

}

export interface StatusCheck {
  enrolType: string,
  aofNo : string,
  requestType: string,
  requestValue: string,
  userId: string,
  additionalData: AdditionalData,
  timeEpoch: string,
  deviceId: string,
  authorization: string,
  userName: string,
  ts: string
}


export interface AdditionalData 
  {
    client_app_ver: string,
    platform: string,
    client_appType: string,
    vendorId: string
  }
 
export interface SignUpload {
  userName: string,
  timeEpoch: string,
  customerId: string,
  accountNo: string,  //long
  encodedSignature: string,  //long
  gatewayUrl: string,
  gatewayTimeout: string,
  gatewayCaCertificate: string,
  key: string,
  cert: string,
}
